# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=40)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=20)),
                ('Description', models.TextField(default='lost item desciption')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
