# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_item',
            name='city',
            field=models.CharField(default='city option', max_length=20),
        ),
        migrations.AlterField(
            model_name='report_item',
            name='location',
            field=models.CharField(max_length=60),
        ),
    ]
