# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-05 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20180804_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_item',
            name='image',
            field=models.FileField(default='add Item image', upload_to=''),
        ),
        migrations.AddField(
            model_name='report_item',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
