# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-05 09:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20180805_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_name', models.CharField(max_length=50)),
                ('Your_mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('Detail_proof', models.TextField()),
            ],
        ),
    ]
