# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20180807_1403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AlterField(
            model_name='report_item',
            name='Description',
            field=models.TextField(help_text='*Enter full description about item'),
        ),
        migrations.AlterField(
            model_name='report_item',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='report_item',
            name='city',
            field=models.CharField(default='city option', help_text='*Enter the city name', max_length=20),
        ),
        migrations.AlterField(
            model_name='report_item',
            name='image',
            field=models.FileField(default='add Item image', help_text='*Please uplocad a item image to identify by the owner', upload_to=''),
        ),
        migrations.AlterField(
            model_name='report_item',
            name='item_name',
            field=models.CharField(help_text='*Enter the item name you found e.g. Marksheet,key,wallet', max_length=50),
        ),
        migrations.AlterField(
            model_name='report_item',
            name='location',
            field=models.CharField(help_text='*Enter the address/street where you find this item', max_length=60),
        ),
    ]
