# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 19:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
