# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_auto_20180813_0051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='usernotification',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report_item',
            name='Description',
            field=models.TextField(blank=True, help_text='*Enter full description about item', null=True),
        ),
    ]
