# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 20:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_auto_20180815_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactHelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=254)),
                ('query', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 8, 16, 20, 58, 5, 668518, tzinfo=utc))),
            ],
        ),
    ]
