# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_contacthelp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacthelp',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
