# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 16:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_auto_20180817_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_item',
            name='image',
            field=models.ImageField(default='add Item image', help_text='*Please uplocad a item image to identify by the owner', upload_to=''),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='Mobile_No',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
