# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_auto_20180820_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_item',
            name='city',
        ),
        migrations.AlterField(
            model_name='report_item',
            name='location',
            field=models.CharField(help_text='*Enter the address and city where you found this item', max_length=60),
        ),
    ]
