# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_auto_20180827_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_item',
            name='image',
            field=models.ImageField(default='add Item image', upload_to=feed.models.get_uplaod_file_name),
        ),
    ]
