# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_auto_20180830_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_item',
            name='slug',
            field=models.SlugField(default='backmyitem-report', unique=True),
        ),
    ]
