# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0020_report_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_item',
            name='slug',
        ),
    ]
