# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0021_remove_report_item_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClaimForm',
        ),
    ]
